DROP TABLE IF EXISTS FILIAIS;
CREATE TABLE IF NOT EXISTS FILIAIS (
    ID INT auto_increment PRIMARY KEY,
    NOME VARCHAR(64),
    ENDERECO VARCHAR (64),
    EH5ESTRELAS BOOLEAN  NOT NULL
    );
